baseurl         = ""
theme           = "casper-two"
languageCode    = "en-US"
#disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Medical Arts Pharmacy"
  subtitle    = "Free Delivery and Free Monthly Planner Packaging "

  cover       = "IMG_3087.JPG"
  description = "Here is a description of your site."
  metaDescription = "medical arts pharmacy, pharmacy, hemp, free delivery, free drug packaging, louisville, great service, counseling, madicare, vaacinations, refills, transfers"
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  #fbName = ""
  githubName = ""
  email = "medicalartspharmacy@gmail.com"

  logo = ""
  orgName = "Medical Arts Pharmacy  1169 Eastern Parkway, Suite 1110, Louisville Kentucky, 40217-1462. Phone:502-709-5532. Fax: 502-371-6659. Hours: Monday to Friday, 8 AM to 5 PM"
  orgWebsite = ""
  orgDescription = "Here is a description placeholder for your org"

  author = "VS"
  authorAvatar = ""
  authorLocation = "Louisville, KY"
  authorWebsite = ""
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper-two"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "https://veeransr.wixsite.com/medicalartspharmacy"
  name = "New_Web_Page"
  weight = 9

[[menu.main]]
  name = "Directions"
  url = "https://www.google.com/maps/place/Medical+Arts+Building,+1169+Eastern+Pkwy+%231110,+Louisville,+KY+40217/@38.2258695,-85.7277053,17z/data=!3m1!4b1!4m5!3m4!1s0x88690d277fe97df9:0x979c453d26b0d25a!8m2!3d38.2258653!4d-85.7255166"
  weight = 1

[[menu.main]]
  name = "Refill"
  url = "https://veeransr.wixsite.com/medicalartspharmacy/refills"
  weight = 4

[[menu.main]]
  name = "Service"
  url = "https://veeransr.wixsite.com/medicalartspharmacy/services-and-products"
  weight = 5
  tags = ["Free Delivery and Free Monthly Planner Packaging"]

[[menu.main]]
  name = "Hemp"
  url = "/hemp/"
  weight = 2

[[menu.main]]
  name = "Transfers"
  url = "https://veeransr.wixsite.com/medicalartspharmacy/transfers"
  weight = 3

[[menu.main]]
  name = "Face_Book"
  url = "https://www.facebook.com/Medical-Arts-Pharmacy-885952964938318"
  weight = 0

